package constants

const TOKEN_KEY = "Authorization"
const RESPONSE_KEY = "RESPONSE_KEY"
const RESPONSE_MESSAGE_KEY = "RESPONSE_MESSAGE_KEY"
const RESPONSE_CODE_KEY = "RESPONSE_CODE_KEY"
const VALIDATED_DTO_DATA = "VALIDATED_DTO_DATA"
